name: John F Howes CPA
favicon: null
layout_spectrum: 0.43604
typography_spectrum: 0.41638
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d8b57f'
    - '#21190e'
    - '#626262'
    - '#f98670'
  brandStrength: 0.75
  lightness: 0.44084754027426243
  saturation: 0.7663308870978653
  rhythmicContrast: 0.2144431855995208
purpose: []
